name: Release Helm Charts

permissions:
  contents: write  # 저장소 쓰기 권한 필요

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/helm-release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Create releases directory
        run: |
          mkdir -p releases

      - name: Package Helm Charts
        run: |
          helm package charts/* --destination releases/

      - name: Create index.yaml
        run: |
          cd releases
          helm repo index --url https://aja2k.github.io/demo/releases/ .

      - name: Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add releases/
          git commit -m "Update Helm charts"
          git push
