name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Create releases directory
        run: |
          mkdir -p releases

      - name: Package Helm Charts
        run: |
          mkdir -p .cr-release-packages
          helm package charts/* --destination .cr-release-packages

      - name: Create index.yaml
        run: |
          helm repo index --url https://aja2k.github.io/demo/releases/ .cr-release-packages

      - name: Move Files
        run: |
          mv .cr-release-packages/* releases/
          mv .cr-release-packages/index.yaml releases/
          rmdir .cr-release-packages

      - name: Push Changes
        run: |
          git add .
          git commit -m "Update Helm charts"
          git push
